Repository Team-JustPay/JustPay-Server, pull requests merged in 2023-01, with the labels that each got.

#2 [#1][FEATURE] #B-1 소셜로그인 API 구현
  .eslintrc.json
  package-lock.json
  package.json
  src/constants/index.ts
  src/constants/response.ts
  src/constants/responseMessage.ts
  src/constants/statusCode.ts
  src/constants/tokenType.ts
  src/controller/userController.ts
  src/index.ts
  src/middlewares/auth.ts
  src/modules/jwtHandler.ts
  src/router/userRouter.ts
  yarn.lock
Labels: :sparkles: feature, 호영, :gun: 리뷰중

#4 [#1][FEATURE] #B-1 소셜로그인 API 구현
  src/controller/authController.ts
  src/controller/userController.ts
  src/router/authRouter.ts
  src/router/userRouter.ts
  tsconfig.json
Labels: :sparkles: feature, 호영

#6 [#3][FEATURE] #C-2 구매 제시하기 API 구현
  .eslintrc.json
  prisma/schema.prisma
  src/constants/responseMessage.ts
  src/controller/index.ts
  src/controller/salespostController.ts
  src/interfaces/salespost/suggestCreateDTO.ts
  src/middlewares/auth.ts
  src/middlewares/upload.ts
  src/modules/shippingOption.ts
  src/router/salespostRouter.ts
  src/service/index.ts
  src/service/salespostService.ts
Labels: :sparkles: feature, 희선, :gun: 리뷰중

#8 [#5][FEATURE] #C-1 판매글 등록 API 구현
  .eslintrc.json
  prisma/schema.prisma
  src/constants/responseMessage.ts
  src/controller/authController.ts
  src/controller/salespostController.ts
  src/interfaces/salespost/salespostCreateDTO.ts
  src/router/salespostRouter.ts
  src/service/index.ts
  src/service/salespostService.ts
  src/service/suggestService.ts
  src/service/userService.ts
Labels: :sparkles: feature, 호영, :gun: 리뷰중

#9 [#7][FEATURE] #C-3 인증 코드 생성 API 구현
  src/constants/responseMessage.ts
  src/constants/wordList.ts
  src/controller/salespostController.ts
  src/router/salespostRouter.ts
  src/service/salespostService.ts
Labels: :sparkles: feature, 희선, :gun: 리뷰중

#15 [#14][FEATURE] #C-7 판매글 상태 변경 (판매 종료)
  src/constants/responseMessage.ts
  src/controller/salespostController.ts
  src/router/salespostRouter.ts
  src/service/salespostService.ts
Labels: :sparkles: feature, 호영, :gun: 리뷰중

#13 [#12][FEATURE] #C-5 인증사진 조회
  src/constants/responseMessage.ts
  src/controller/salespostController.ts
  src/router/salespostRouter.ts
  src/service/salespostService.ts
Labels: :sparkles: feature, 호영, :gun: 리뷰중

#21 [#17][FEATURE] #C-6 판매글 구매 제시 목록 (매칭중, 매칭완료) API 구현
  src/constants/responseMessage.ts
  src/controller/salespostController.ts
  src/interfaces/salespost/getPurchaseListDTO.ts
  src/router/salespostRouter.ts
  src/service/salespostService.ts
Labels: :sparkles: feature, 희선, :gun: 리뷰중

#18 [#16][FEATURE] #B-7 내 판매중 정보 조회
  src/constants/responseMessage.ts
  src/controller/userController.ts
  src/router/userRouter.ts
  src/service/userService.ts
Labels: :sparkles: feature, 호영, :gun: 리뷰중

#20 [#19][FEATURE] #C-7 배송 정보 확인
  src/constants/responseMessage.ts
  src/controller/suggestController.ts
  src/router/suggestRouter.ts
  src/service/suggestService.ts
Labels: :sparkles: feature, 호영, :gun: 리뷰중

#24 [#22][FEATURE] #D-2 구매 제시 삭제 API 구현
  src/constants/responseMessage.ts
  src/controller/suggestController.ts
  src/router/suggestRouter.ts
  src/service/suggestService.ts
Labels: :sparkles: feature, 희선

#25 [#23][FEATURE] #C-4 판매글 정보 조회 (+판매글 상세 조회)
  src/constants/responseMessage.ts
  src/constants/shippingInfo.ts
  src/controller/salespostController.ts
  src/router/salespostRouter.ts
  src/service/salespostService.ts
Labels: :sparkles: feature, 호영, :gun: 리뷰중

#31 [#28][FEATURE] #D-4 구매 제시 가격 올리기
  src/constants/responseMessage.ts
  src/controller/suggestController.ts
  src/router/suggestRouter.ts
  src/service/suggestService.ts
Labels: :sparkles: feature, 희선

#35 [#34][FEATURE] #B-6 내 구매중 정보조회 API 구현
  src/constants/responseMessage.ts
  src/controller/userController.ts
  src/router/userRouter.ts
  src/service/userService.ts
Labels: :sparkles: feature, 희선, :gun: 리뷰중

#37 [#36][FEATURE] #B-3 내 정보 수정
  src/controller/userController.ts
  src/interfaces/user/userUpdateDTO.ts
  src/router/userRouter.ts
  src/service/userService.ts
Labels: :sparkles: feature, 호영, :gun: 리뷰중

#40 [#38][FEATURE] #D-0 결제 정보 조회
  src/constants/responseMessage.ts
  src/controller/suggestController.ts
  src/modules/date.ts
  src/router/suggestRouter.ts
  src/service/suggestService.ts
Labels: :sparkles: feature, 호영, :gun: 리뷰중

#41 [#39][FEATURE] #D-3 구매 제시 상태 변경
  src/constants/responseMessage.ts
  src/controller/suggestController.ts
  src/router/suggestRouter.ts
  src/service/suggestService.ts
Labels: :sparkles: feature, 희선, :gun: 리뷰중

#47 feat: add createNotification
  src/modules/notification.ts
Labels: :sparkles: feature, 호영

#44 [#43][FEATURE] #D-1 구매 제시 내용 조회
  src/constants/responseMessage.ts
  src/controller/suggestController.ts
  src/router/suggestRouter.ts
  src/service/suggestService.ts
Labels: :sparkles: feature, 희선, :gun: 리뷰중

#48 [#45][FEATURE] #D-6 운송장 번호 확인 API 구현 & #B-5 내 알리미 조회 API 구현
  src/constants/responseMessage.ts
  src/controller/suggestController.ts
  src/controller/userController.ts
  src/modules/date.ts
  src/modules/dateNotification.ts
  src/router/suggestRouter.ts
  src/router/userRouter.ts
  src/service/suggestService.ts
  src/service/userService.ts
Labels: :sparkles: feature, 희선, :gun: 리뷰중

#49 알리미 생성
  src/constants/notification.ts
  src/controller/suggestController.ts
  src/service/suggestService.ts
Labels: :sparkles: feature, 호영

#54 Husky, Jest 세팅
  .eslintrc.json
  .husky/pre-commit
  jest.config.js
  package.json
  tests/users.test.ts
  tsconfig.json
  yarn.lock
Labels: :sparkles: feature, 희선

#55 [FEATURE] Suggests 라우트 테스트 코드 작성
  __test__/salesposts.test.ts
  __test__/suggests.test.ts
  src/db/data.ts
Labels: :sparkles: feature, 희선

#56 [FEATURE] Users 라우트 테스트코드 작성
  __test__/auth.test.ts
  __test__/salesposts.test.ts
  __test__/suggests.test.ts
  __test__/users.test.ts
  src/db/data.ts
  src/interfaces/user/userUpdateDTO.ts
  src/modules/testModule.ts
Labels: :sparkles: feature, 희선

#57 [FEATURE] salesposts 라우트 테스트코드 작성
  __test__/salesposts.test.ts
  assets/img/just_pay.png
  jest.config.js
  src/controller/salespostController.ts
  src/modules/testModule.ts
Labels: :sparkles: feature, 희선

#60 예외처리 상세 추가
  src/constants/responseMessage.ts
  src/controller/salespostController.ts
  src/controller/suggestController.ts
  src/controller/userController.ts
  src/modules/existCheck.ts
Labels: :sparkles: feature, 호영
